# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }


gem "tty-box", "~> 0.5.0"
gem "tty-font", "~> 0.5.0"
gem "colorize", "~> 0.8.1"
